image: comp1531/basic:latest

cache:
  paths:
    - node_modules

stages:
  - checks
    
before_script:
  - npm install

testing:
  stage: checks
  script:
    - npm run test

linting:
  stage: checks
  script:
    - npm run lint
